from setuptools import setup, find_packages

setup(
    name='SMNAMonitoringApp',
    version='0.0.0a1',
    author='Carlos Frederico Bastarz',
    author_email='carlos.bastarz@inpe.br',
    url = "https://github.com/GAD-DIMNT-CPTEC/SMNAMonitoringApp",
    license = "CC BY-NC-SA-4.0",
    long_description=open('README.md').read(),
    long_description_content_type='text/markdown',
    description='SMNAMonitor Monitoring App for the SMNA data assimilation system.',
    keyword=['gridpoint statistical interpolation', 'data assimilation', 'brazilian atmospheric model', 'numerical weather prediction'],
    packages=find_packages(),
    install_requires=[
        'numpy>=1.22',
        'xarray>=2024.2.0',
        'dask',
        'dask_expr',
        'datashader',
        'seaborn',
        'Cartopy==0.22.0',
        'matplotlib==3.8.3',
        'matplotlib-inline==0.1.6',
        'panel==1.3.8',
        'intake==0.7.0',
        'intake-geopandas==0.4.0',
        'intake-xarray>=0.7.0',
        'hvplot>=0.9.2',
        'geoviews>=1.11.1',
        'requests>=2.31.0',
        'aiohttp>=3.9.3',
        'markdown==3.5.2',
        'param==2.0.2',
        'pyarrow==15.0.0',
        'scipy==1.12.0',
        'wheel==0.42.0',
        'zarr==2.17.0',
        ],
    extra_requires={'dev': ['twine>=4.0.2']},
    classifiers=[
        'Programming Language :: Python :: 3',
        'License :: OSI Approved :: MIT License',
        'Operating System :: OS Independent',
    ],
    scripts=['SMNAMonitoringApp', 
             'monitor.py',
             'monitor_about.py',
             'monitor_anl.py',
             'monitor_armobs.py',
             'monitor_cstatus.py',
             'monitor_dates.py',
             'monitor_floatpanel.py',
             'monitor_info.py',
             'monitor_jo.py',
             'monitor_logs.py',
             'monitor_mass.py',
             'monitor_modal.py',
             'monitor_texts.py',
             'monitor_rdiag.py',
             'monitor_mass.py',
             'monitor_berror.py',
             ],
    python_requires='>=3.12',
)
